### PR TITLE
use shorthand int and float types

### PR DESCRIPTION
**Pull request by StarrFox**
int8 -> s8

float32 -> f32

### CODE REVIEW

**Review by StarrFox — COMMENTED** [review]
not sure what to do about the special `int`; should it just be removed?

**Comment by SirOlaf** [comment]
s32 -> i32. PR will be rejected otherwise

**Review by SirOlaf — CHANGES_REQUESTED** [review]
sX must be iX. Also why are most of the tests unsigned now

**Comment by StarrFox** [comment]
> sX must be iX. Also why are most of the tests unsigned now

why wouldn't they be unsigned

**Comment by StarrFox** [comment]
you guys can keep coping with int32

**Pull request closed without merging**
